### ISSUE TITLE
Technical discovery of FMP roadmap

### ISSUE THREAD

**Issue by jduss4** [18F/gsa-small-business-experience#114]
- [x] investigate activities around GSA.gov content
- [x] investigate feasibility of taking on small business project long term
- [x] determine if we should pursue conversations with Mauri and FAS GSA.gov team or digital experience

[Notes](https://docs.google.com/document/d/1q6Nc_VmafHy-dv5Q_WxknZvqjfTZH_djye3joOI0D-4/edit#heading=h.s7fqab4qkvh4) 🔐
