### ISSUE TITLE
Prepare prototype for testing

### ISSUE THREAD

**Issue by cmajel** [18F/gsa-small-business-experience#62]
**Background**
We want to test our early ideas with small businesses, and this ticket is the logistics of getting these ideas into a testable form. Expect this work will take place the weeks of 3/14-3/21.

**Task**
- [ ] Identify which wireframe concepts we want to move to testing
- [ ] Sync with dev on options for a coded prototype
- [ ] Create prototype (in code or Invision)
- [ ] Review with partners (#65)
- [ ] ???

**Done when**
- [ ] We have a prototype link or asset that's ready to be shared with participants

**Comment by cmajel** [comment]
👍🏻  That works for me. I suspect we'll have a better idea of what "develop & build" options we have once we sync with @jduss4 .

**Comment by cmajel** [comment]
Closing as duplicative to dev tickets
