### ISSUE TITLE
Prepare research plan and script for first design test

### ISSUE THREAD

**Issue by cmajel** [18F/gsa-small-business-experience#64]
**Background**
We want to continue learning about small business experiences and test our initial design concepts. 

**Tasks**
- [x] Update [draft plan](https://docs.google.com/document/d/1Vt35oGKEx6JpR0_zJI3D9ZCS467DmoVjUITFfLfK1q4/edit#)
- [x] Cross check with [18F research plan template](https://github.com/18F/ux-guide/blob/master/_pages/resources/research-plan.md), and make sure we're hitting main points
- [x] Determine if there are concepts from the FAS project that are worth exploring (knowledge center, feedback form)
- [x] [Write Script](https://docs.google.com/document/d/1Kh2bOr5-WxIgzVymAeiAE8yqZdm-fyxFqanbWGrG5vg/edit#) - So any team member is able to moderate (intros, consent and framing, questions/prompts, links to assets)
- [x] Review with partners (#65)

**Done when**
- [x] We have a research plan that's reviewed by the team (is this the right done definition?)

**Comment by cmajel** [comment]
This will be set after we update the roles based on coworking today. cc @janelx
