### ISSUE TITLE
Review prototype and research plan with partners

### ISSUE THREAD

**Issue by cmajel** [18F/gsa-small-business-experience#65]
**Background**
We want to keep partners informed on where we're heading. This is a place to preview what we're planning on testing.

**Tasks**
- [x] Set up meetings with OSDBU, FAS, OSC (one meeting? multiple?)
- [x] Have meeting
- [x] Identify if changes are needed

**Done when:**
- [x] The prototype and research plan has been reviewed by partners
