### ISSUE TITLE
Hold first design test sessions

### ISSUE THREAD

**Issue by cmajel** [18F/gsa-small-business-experience#67]
**Background**
We'll be testing early design work with small business, and this is a place to hold tasks and logistics when sessions take place.

**Tasks**
- [x] Have facilitator and note takers identified
- [x] Schedule Debrief with observers
- [x] Decide Synthesis approach
- [x] Identify what iterations are needed for next round of testing

**Done when**
- [x] We know what to change for the next round of testing.
Schedule time on team meeting.

**Comment by janelx** [comment]
@cmajel this is my general process for user research, particularly user testing. Let me know what you think and we can edit and break these down into tasks.

- [ ] Script
- [ ] Observation outline or form - this to capture observations for debrief
- [ ] Review findings, observations > Identify user pain points and what went well
- [ ] List iteration recommendations (if needed, hold co-design session on for tougher problems)
- [ ] Review iteration recommendations with team, holders and capture additional changes
- [ ] Design needed iterations

**Comment by janelx** [comment]
Once we schedule the testing we can also send out invite to people to view and be observers (with observation form) or send out recordings for anyone with the observation form.

**Comment by cmajel** [comment]
Nice, thanks for sharing. A few comments:
* I mentioned the script in the [research planning ticket](https://github.com/18F/gsa-small-business-experience/issues/64), and updated it with your language. Does that feel like the right place?
* Observation -  design needed iterations look good (I'm more familiar with in-person debriefs so am interested in the form). My instinct is to keep this ticket for interview conducting and moderation, and make new tickets for synthesis / review items, and a placeholder for design iterations. 
* Let's talk more about how to involve observers in synthesis at a coworking.
